apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wled-gradients-data
  namespace: wled-gradients
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
