apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-tailscale
  namespace: pihole-tailscale
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole-tailscale.doma.lol`)
      services:
        - name: pihole-tailscale-web
          port: 80
