apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies-ro
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
  volumeName: pv-movies-ro
