apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-smb-secret-access-binding
  namespace: jellyfin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-smb-secret-access
subjects:
  - kind: ServiceAccount
    name: csi-smb-node-sa
    namespace: csi-driver-smb
