apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-smb-secret-access
  namespace: jellyfin
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
