apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.doma.lol`)
      middlewares:
        - name: longhorn-auth
      services:
        - name: longhorn-frontend
          port: 80
