apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.doma.lol
    external-dns.alpha.kubernetes.io/target: homelab.boreal-scala.ts.net
  name: longhorn-tailscale
  namespace: longhorn
spec:
  clusterIP: None
  type: ClusterIP
