apiVersion: v1
data:
  config.json: '{"endpoint":"https://forgejo.doma.lol","gitAuthor":"Renovate Bot <renovate@doma.lol>","platform":"forgejo","repositories":["miro/dazzle","miro/homelab"]}'
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
