apiVersion: v1
data:
  users.xml: |-
    <?xml version="1.0"?>
    <clickhouse>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>in_order</load_balancing>
                <log_queries>1</log_queries>
            </default>
            <readonly>
                <readonly>2</readonly>
            </readonly>
        </profiles>

        <users>
            <default>
                <password></password>
                <profile>default</profile>
                <networks>
                    <ip>::1</ip>
                    <ip>127.0.0.1</ip>
                </networks>
                <quota>default</quota>
            </default>
            <app>
                <password>hyperdx</password>
                <networks>
                    <ip>10.0.0.0/8</ip>
                    <ip>172.16.0.0/12</ip>
                    <ip>192.168.0.0/16</ip>
                    <host_regexp>.*\.svc\.cluster\.local$</host_regexp>
                </networks>
                <profile>readonly</profile>
                <quota>default</quota>
                <grants>
                    <query>GRANT SHOW ON *.*</query>
                    <query>GRANT SELECT ON system.*</query>
                    <query>GRANT SELECT ON default.*</query>
                </grants>
            </app>
            <otelcollector>
                <password>otelcollectorpass</password>
                <networks>
                    <ip>10.0.0.0/8</ip>
                    <ip>172.16.0.0/12</ip>
                    <ip>192.168.0.0/16</ip>
                    <host_regexp>.*\.svc\.cluster\.local$</host_regexp>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
                <grants>
                    <query>GRANT SELECT,INSERT,CREATE,SHOW ON default.*</query>
                </grants>
            </otelcollector>
        </users>

        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: hyperdx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hdx-oss-v2
    app.kubernetes.io/version: 2.6.0
    helm.sh/chart: hdx-oss-v2-0.7.3
  name: hyperdx-hdx-oss-v2-clickhouse-users
  namespace: hyperdx
