apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: otel-deployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: opentelemetry-collector
    app.kubernetes.io/version: 0.138.0
    helm.sh/chart: opentelemetry-collector-0.138.0
  name: otel-deployment-opentelemetry-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-deployment-opentelemetry-collector
subjects:
  - kind: ServiceAccount
    name: otel-deployment-opentelemetry-collector
    namespace: otel
