apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: agent-collector
    app.kubernetes.io/instance: otel-daemonset
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/part-of: opentelemetry-collector
    app.kubernetes.io/version: 0.138.0
    helm.sh/chart: opentelemetry-collector-0.138.0
  name: otel-daemonset-opentelemetry-collector-agent
  namespace: otel
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: otel-daemonset
      app.kubernetes.io/name: opentelemetry-collector
      component: agent-collector
  template:
    metadata:
      annotations:
        checksum/config: 4f9b651da4464ccd75f8ec38fac398040ca814dc215fcd83d5e82b0bc490f7ea
      labels:
        app.kubernetes.io/instance: otel-daemonset
        app.kubernetes.io/name: opentelemetry-collector
        component: agent-collector
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --config=/conf/relay.yaml
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HYPERDX_API_KEY
              valueFrom:
                secretKeyRef:
                  key: HYPERDX_API_KEY
                  name: hyperdx-ingestion
                  optional: true
            - name: YOUR_OTEL_COLLECTOR_ENDPOINT
              value: http://hyperdx-hdx-oss-v2-otel-collector.hyperdx.svc.cluster.local:4318
          image: otel/opentelemetry-collector-contrib:0.138.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          name: opentelemetry-collector
          ports:
            - containerPort: 6831
              hostPort: 6831
              name: jaeger-compact
              protocol: UDP
            - containerPort: 14250
              hostPort: 14250
              name: jaeger-grpc
              protocol: TCP
            - containerPort: 14268
              hostPort: 14268
              name: jaeger-thrift
              protocol: TCP
            - containerPort: 4317
              hostPort: 4317
              name: otlp
              protocol: TCP
            - containerPort: 4318
              hostPort: 4318
              name: otlp-http
              protocol: TCP
            - containerPort: 9411
              hostPort: 9411
              name: zipkin
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          securityContext: {}
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
            - mountPath: /var/log/pods
              name: varlogpods
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /hostfs
              mountPropagation: HostToContainer
              name: hostfs
              readOnly: true
      hostNetwork: false
      securityContext: {}
      serviceAccountName: otel-daemonset-opentelemetry-collector
      volumes:
        - configMap:
            items:
              - key: relay
                path: relay.yaml
            name: otel-daemonset-opentelemetry-collector-agent
          name: opentelemetry-collector-configmap
        - hostPath:
            path: /var/log/pods
          name: varlogpods
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - hostPath:
            path: /
          name: hostfs
  updateStrategy:
    type: RollingUpdate
