apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/version: 1.3.0
    helm.sh/chart: alloy-operator-0.3.11
  name: grafana-k8s-monitoring-alloy-operator
  namespace: grafana-k8s-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-k8s-monitoring
      app.kubernetes.io/name: alloy-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grafana-k8s-monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: alloy-operator
        app.kubernetes.io/version: 1.3.0
        helm.sh/chart: alloy-operator-0.3.11
    spec:
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8082
            - --leader-elect
            - --leader-election-id=grafana-k8s-monitoring-alloy-operator
          image: ghcr.io/grafana/alloy-operator:1.3.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: alloy-operator
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 8082
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits: {}
            requests: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: grafana-k8s-monitoring-alloy-operator
