apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/name: grafana-k8s-monitoring-remove-alloy-and-finalizer
    helm.sh/chart: k8s-monitoring-3.5.5
  name: grafana-k8s-monitoring-remove-alloy-and-finalizer
  namespace: grafana
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grafana-k8s-monitoring
        app.kubernetes.io/name: grafana-k8s-monitoring
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      name: grafana-k8s-monitoring-remove-alloy-and-finalizer
    spec:
      containers:
        - command:
            - /bin/bash
            - -ce
            - |
              echo "Deleting Alloy instance: alloy/grafana-k8s-monitoring-alloy-metrics..."
              kubectl delete alloy/grafana-k8s-monitoring-alloy-metrics --ignore-not-found=true --wait
              kubectl wait --for=delete alloy/grafana-k8s-monitoring-alloy-metrics --timeout=60s || echo "Timed out waiting for deletion of alloy/grafana-k8s-monitoring-alloy-metrics or it may not exist."

              kubectl patch \
                --namespace=grafana \
                --type json \
                --patch='[{"op": "remove", "path": "/metadata/finalizers"}]' \
                deployment/grafana-k8s-monitoring-alloy-operator
          image: ghcr.io/grafana/helm-chart-toolbox-kubectl:0.1.1
          imagePullPolicy: IfNotPresent
          name: remove-finalizers
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 4242
            seccompProfile:
              type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: grafana-k8s-monitoring-remove-alloy-and-finalizer
  ttlSecondsAfterFinished: 300
