apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: windows-exporter
    app.kubernetes.io/part-of: windows-exporter
    app.kubernetes.io/version: 0.31.3
    helm.sh/chart: windows-exporter-0.12.2
    release: grafana-k8s-monitoring
  name: grafana-k8s-monitoring-windows-exporter
  namespace: grafana-k8s-monitoring
spec:
  ports:
    - appProtocol: http
      name: metrics
      port: 9182
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/name: windows-exporter
  type: ClusterIP
