apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: node-exporter
    app.kubernetes.io/version: 1.9.1
    helm.sh/chart: node-exporter-4.48.0
    release: grafana-k8s-monitoring
  name: grafana-k8s-monitoring-node-exporter
  namespace: grafana-k8s-monitoring
