apiVersion: v1
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
    dhcp-option=6,10.42.1.250
  05-pihole-custom-cname.conf: ""
  addn-hosts: ""
kind: ConfigMap
metadata:
  labels:
    app: pihole
    chart: pihole-2.34.0
    heritage: Helm
    release: pihole
  name: pihole-custom-dnsmasq
  namespace: pihole
