apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
    chart: pihole-2.34.0
    component: ""
    heritage: Helm
    release: pihole
  name: pihole
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
