apiVersion: v1
data:
  password: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: pihole
    chart: pihole-2.34.0
    heritage: Helm
    release: pihole
  name: pihole-password
  namespace: pihole
type: Opaque
