apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: csi-driver-smb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-smb
    app.kubernetes.io/version: 1.18.0
    helm.sh/chart: csi-driver-smb-1.18.0
  name: csi-smb-node-secret-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
