apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "15"
  labels:
    app.kubernetes.io/instance: k8s-monitoring
    app.kubernetes.io/name: k8s-monitoring-add-finalizer
    helm.sh/chart: k8s-monitoring-3.5.5
  name: k8s-monitoring-add-finalizer
  namespace: monitoring
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: k8s-monitoring
        app.kubernetes.io/name: k8s-monitoring
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      name: k8s-monitoring-add-finalizer
    spec:
      containers:
        - command:
            - /bin/bash
            - -ce
            - |
              kubectl patch \
                --namespace=monitoring \
                --patch='{"metadata":{"finalizers":["k8s.grafana.com/finalizer"]}}' \
                deployment/k8s-monitoring-alloy-operator
          image: ghcr.io/grafana/helm-chart-toolbox-kubectl:0.1.1
          imagePullPolicy: IfNotPresent
          name: add-finalizers
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 4242
            seccompProfile:
              type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: k8s-monitoring-add-finalizer
  ttlSecondsAfterFinished: 300
