apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/version: 1.3.0
    helm.sh/chart: alloy-operator-0.3.11
  name: k8s-monitoring-alloy-operator-leader-election-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-monitoring-alloy-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: k8s-monitoring-alloy-operator
    namespace: monitoring
