apiVersion: v1
data:
  admin-password: Wm9tNlRxckU3cGR3dlh1VFRkZDNWSjlDNEc4Rk9nZHc5bWNhQnREMA==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.1
    helm.sh/chart: grafana-10.5.15
  name: grafana
  namespace: monitoring
type: Opaque
