apiVersion: v1
data:
  rootPassword: c3VwZXJzZWNyZXRwYXNzd29yZA==
  rootUser: cm9vdC11c2Vy
kind: Secret
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    release: loki
  name: loki-minio
  namespace: monitoring
type: Opaque
