apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    monitoring: "true"
    release: loki
  name: loki-minio
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: loki
  type: ClusterIP
