apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: k8s-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/version: 1.3.0
    helm.sh/chart: alloy-operator-0.3.11
  name: k8s-monitoring-alloy-operator
  namespace: monitoring
