apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.doma.lol
    external-dns.alpha.kubernetes.io/target: homelab-1.boreal-scala.ts.net
  name: grafana-tailscale
  namespace: monitoring
spec:
  clusterIP: None
  type: ClusterIP
