apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-doma-lol
  namespace: traefik
spec:
  dnsNames:
    - doma.lol
    - '*.doma.lol'
  issuerRef:
    kind: Issuer
    name: cloudflare-issuer
  secretName: wildcard-doma-lol-tls
