apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: lissy93/dashy@sha256:f656ea52c16801a5e9a80353616b76a8537e4d1a73900cb0ecfae786ce7ddf66
          name: dashy
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /app/user-data
              name: config
              readOnly: true
      volumes:
        - configMap:
            name: dashy-config
          name: config
