apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: lissy93/dashy@sha256:c663b870e60b967906830623ab76b09d1bd48801f50c53e95da1bc0c27e5bd96
          name: dashy
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /app/user-data
              name: config
              readOnly: true
      volumes:
        - configMap:
            name: dashy-config
          name: config
