apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashy
  namespace: dashy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dashy.doma.lol`)
      services:
        - name: dashy
          port: 80
  tls:
    certResolver: letsencrypt
    domains:
      - main: doma.lol
        sans:
          - '*.doma.lol'
