apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: cloudnativepg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/version: 1.27.0
    helm.sh/chart: cloudnative-pg-0.26.0
  name: cloudnativepg-cloudnative-pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnativepg-cloudnative-pg
subjects:
  - kind: ServiceAccount
    name: cloudnativepg-cloudnative-pg
    namespace: cnpg-system
