apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-paa-certs-data
  namespace: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
