apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ts
  namespace: pihole-ts
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.doma.lol`)
      services:
        - name: pihole-ts-web
          port: 80
