apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
