apiVersion: v1
data:
  admin-password: RUpTcDhFdXJiYjJmT1Z0bjk5ZFdZZFkyVGk1SUpxQU5NeUNzaU5UUA==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.2.0
    helm.sh/chart: grafana-10.1.2
  name: grafana
  namespace: grafana
type: Opaque
