apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  namespace: forgejo
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`forgejo.doma.lol`)
      services:
        - name: forgejo-http
          port: 3000
  tls:
    certResolver: letsencrypt
    domains:
      - main: doma.lol
        sans:
          - '*.doma.lol'
