apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.5
    helm.sh/chart: loki-6.44.0
  name: grafana-loki-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-loki-clusterrole
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: grafana-loki
