apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
  labels:
    app: minio-post-job
    chart: minio-5.4.0
    heritage: Helm
    release: grafana-loki
  name: grafana-loki-minio-post-job
  namespace: grafana-loki
spec:
  template:
    metadata:
      labels:
        app: minio-job
        release: grafana-loki
    spec:
      containers:
        - command:
            - /bin/sh
            - /config/initialize
          env:
            - name: MINIO_ENDPOINT
              value: grafana-loki-minio
            - name: MINIO_PORT
              value: "9000"
          image: quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z
          imagePullPolicy: IfNotPresent
          name: minio-make-bucket
          resources:
            requests:
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/minio/mc
              name: etc-path
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: minio-configuration
        - command:
            - /bin/sh
            - /config/add-user
          env:
            - name: MINIO_ENDPOINT
              value: grafana-loki-minio
            - name: MINIO_PORT
              value: "9000"
          image: quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z
          imagePullPolicy: IfNotPresent
          name: minio-make-user
          resources:
            requests:
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/minio/mc
              name: etc-path
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: minio-configuration
      restartPolicy: OnFailure
      serviceAccountName: minio-sa
      volumes:
        - emptyDir: {}
          name: etc-path
        - emptyDir: {}
          name: tmp
        - name: minio-configuration
          projected:
            sources:
              - configMap:
                  name: grafana-loki-minio
              - secret:
                  name: grafana-loki-minio
