apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    monitoring: "true"
    release: grafana-loki
  name: grafana-loki-minio
  namespace: grafana-loki
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: grafana-loki
  type: ClusterIP
