apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.5
    helm.sh/chart: loki-6.44.0
    prometheus.io/service-monitor: "false"
    variant: headless
  name: loki-headless
  namespace: grafana-loki
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
