apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    release: grafana-loki
  name: grafana-loki-minio-console
  namespace: grafana-loki
spec:
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: grafana-loki
  type: ClusterIP
