apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.5
    helm.sh/chart: loki-6.44.0
  name: grafana-loki
  namespace: grafana-loki
spec:
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: single-binary
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
  type: ClusterIP
