apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    chart: minio-5.4.0
    heritage: Helm
    release: grafana-loki
  name: grafana-loki-minio-svc
  namespace: grafana-loki
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  publishNotReadyAddresses: true
  selector:
    app: minio
    release: grafana-loki
