apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.5
    helm.sh/chart: loki-6.44.0
    prometheus.io/service-monitor: "false"
  name: grafana-loki-gateway
  namespace: grafana-loki
spec:
  ports:
    - name: http-metrics
      port: 80
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: grafana-loki
    app.kubernetes.io/name: loki
  type: ClusterIP
