apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inteldeviceplugins-leader-election-rolebinding
  namespace: intel-device-plugins-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inteldeviceplugins-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: intel-device-plugins-operator
