apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: whisper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
