apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: homelab-1.boreal-scala.ts.net
  name: immich-ts
  namespace: immich
spec:
  ingressClassName: external-dns-ts
  rules:
    - host: immich.doma.lol
