apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-rw
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: smb
  volumeName: pv-immich-rw
