apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos-ro
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
  volumeName: pv-photos-ro
