apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich.doma.lol
    external-dns.alpha.kubernetes.io/target: homelab-1.boreal-scala.ts.net
  name: immich-ts
  namespace: immich
spec:
  clusterIP: None
  type: ClusterIP
