apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-config
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/coredns-config
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
