apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  destination:
    namespace: otel
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/otel
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
