apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-ts
  namespace: argocd
spec:
  destination:
    namespace: external-dns-ts
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/external-dns-ts
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
