apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/monitoring
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
