apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
spec:
  destination:
    namespace: grafana-loki
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/grafana-loki
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
