apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/sealed-secrets
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: master
  syncPolicy: {}
