apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kata
  namespace: argocd
spec:
  destination:
    namespace: kata-containers
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k3s/generated_manifests/kata
    repoURL: https://github.com/mirosval/homelab.git
    targetRevision: main
  syncPolicy: {}
